alias l='ls -al'
alias u='cd ..'
alias uu='cd ../..'
alias uuu='cd ../../..'
alias uuuu='cd ../../../..'

# Latex
alias latexmk_='latexmk -pdf -pvc'
function pdflatex-watch() { while true; do inotifywait -e modify "$1"; pdflatex "$1"; done;}

export EDITOR=vim
export WORKON_HOME=~/.virtualenvs
# export TERM=screen-256color
export R_HOME=/Library/Frameworks/R.framework/Resources
export JAVA_HOME=$(/usr/libexec/java_home)
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH
# .zshrc
# alias tmux="TERM=screen-256color tmux"
alias tmux="TERM=screen-256color tmux"
export LANG=en_US.UTF-8

stty -ixon

if [ `uname` = "Darwin" ]; then
    # autostart virtual env
    export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
    source /usr/local/bin/virtualenvwrapper.sh

    alias ipy="python -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'"

    alias cdcb='cd ~/Dropbox/CBB/ComputationalBiology'
    alias cdcsb='cd ~/Dropbox/CBB/ComputationalSystemsBiology'
    alias cded='cd ~/Dropbox/CBB/EvolutionaryDynamics'
    alias cdml='cd ~/Dropbox/CBB/MachineLearning'
fi

