#!/usr/bin/env zsh

set -x

# ====== Variables =============================
declare -A color

color["focused"]="0xFFFF8800"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# ===== Loading Scripting Additions ============
# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ===== Tiling setting =========================
# .. more yabai startup stuff
yabai -m config debug_output on

yabai -m config top_padding    1
yabai -m config bottom_padding 1
yabai -m config left_padding   1
yabai -m config right_padding  1
yabai -m config window_gap     1

yabai -m config window_border               on
yabai -m config window_border_width         4
yabai -m config active_window_border_color  "${color["focused"]}"
yabai -m config normal_window_border_color  "${color["normal"]}"
yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config window_topmost              off
yabai -m config window_opacity              off

# Only floating windows have shadows
yabai -m config window_shadow float

yabai -m config layout bsp

# New window spawns to the left if vertical split, or top if horizontal split
yabai -m config window_placement first_child

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# on or off (default: off)
yabai -m config auto_balance off

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autoraise

# floating windows are always on top (default: off)
yabai -m config window_topmost on

# ===== Rules ==================================
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
